server:
  port: 8712
spring:
  application:
    name: Service-Provider
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ok
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.11.114:8711/eureka/


mybatis:
  mapper-locations: classpath:mappings/*.xml